---
- name: Exercise 4a
  hosts: nxos
  gather_facts: False
  vars: 
    command: show interface
  collections:
  - clay584.genie

  tasks:
  - name: Run command
    nxos_command:
      commands: "{{ command }}"
    register: output

  - debug:
      var: output

  - set_fact:
      output_struct: "{{ output.stdout[0] | clay584.genie.parse_genie(command=command, os='nxos') }}"

  - debug:
      msg: "{{ output_struct }}"
