---
- name: Exercise 5b
  gather_facts: False
  hosts: arista
  vars: 
    command: "show version"

  tasks:
  - name: do command
    eos_command:
      commands: "{{ command }}"
    register: output

  - name: facts1
    set_fact:
      show_ver: "{{output.stdout[0] }}"

  - debug:
      msg: "{{ show_ver }}"


  - name: get info
    set_fact:
#      version: "{{ show_ver | regex_findall('(^Software.*)', multiline=True) }}"
      version: "{{ show_ver | regex_findall('^Software\\s+image\\s+ver\\S+\\s+(\\S+)', multiline=True) }}"
#                                               Software image version: 4.20.10M\n
  - debug:
      msg: "{{ version }}"
    
    
#  - debug:
#      msg: "{{ show_lldp_no_fline }}"
#  
#  - name: strip info line 2
#    set_fact:
#      show_lldp_no_sline: "{{ show_lldp_no_fline | regex_replace('\\(R\\) Router.*Device') | trim }}"
#    
#  - debug:
#      msg: "{{ show_lldp_no_sline }}"
#
#  - name: strip info line 3
#    set_fact:
#      show_lldp_no_tline: "{{ show_lldp_no_sline | regex_replace('\\(R\\) Router.*Device') | trim }}"
#    
#  - debug:
#      msg: "{{ show_lldp_no_tline }}"
