---
- name: exercise 2
  gather_facts: False
  hosts: arista
  tasks:
  - block:
    - name: try eosconfig with wrong passwd
      eos_config:
        commands:
         - ip name-server 1.1.1.1
         - ip name-server 1.1.1.2
    vars:
      ansible_ssh_pass: "invalid"
    rescue:
    - name: try eosconfig with wrong passwd
      eos_config:
        commands:
          - ip name-server 1.1.1.1
          - ip name-server 1.1.1.2
      vars:
        # Use environment variable to avoid hard-coded passwd
        ansible_ssh_pass: "{{lookup('env','ANSIBLE_PASSWORD')}}"


