---
- name: excercise 3
  hosts: cisco
  vars:
    - ntp_server1: 130.126.24.24
    - ntp_server2: 152.2.21.1
    - domain_name: bogus.com
    - dns_server1: 8.8.8.8
    - dns_server2: 8.8.4.4
  tasks:
  - name: Cisco IOS config DNS/NTP/domain-name
    import_tasks: subtask3a.yml
    when: ansible_facts.net_iostype == "IOS"

  - name: Cisco IOS-XE config DNS/NTP/domain-name
    import_tasks: subtask3b.yml
    when: ansible_facts.net_iostype == "IOS-XE"
