---
- name: Exercise 2 nxos
  gather_facts: False
  hosts: nxos1
  tasks:
    - name: do the looptheloop
      loop:
        - 1
        - 2
        - 3
        - 4
      nxos_command:
        commands: "show vlan id {{ item }}"
      register: vlans

    - name: print vlan 4 output
      debug:
       # msg: test
        msg: "{{ vlans.results[3].stdout_lines }}"

