---
- name: number 3
  gather_facts: False
  hosts: cisco1:cisco2
  tasks:
  - name: do show lldp neighbor command
    ios_command:
      commands: show lldp neighbor
    register: lldp_result

  - name: neighbor part of lldp
    #debug:
    #  msg: "{{ item }}"
    set_fact: 
      lldp_entry: "{{ item }}"
    loop: "{{ lldp_result.stdout_lines[0] }}"
    when: item.find('twb-sf-hpsw1') == 0

  - name: facts
    set_fact:
      remote_device: "{{ lldp_entry.split()[0] }}"
      local_intf: "{{ lldp_entry.split()[1] }}"
      remote_intf: "{{ lldp_entry.split()[4] }}"

  - name: print info out to screen
    debug:
      msg: 
        - 'Remote device: {{remote_device}}'
        - 'Local interface: {{local_intf}}'
        - 'Remote interface: {{remote_intf}}'

