---
- name: create nxos config from j2 template files
  hosts: nxos
  gather_facts: False
  tasks:
    - name: create interfaces configs
      template:
        src: nxos_interfaces.j2
        dest: "./configs/tmp/{{ inventory_hostname }}_1_interfaces.txt"
    - name: create bgp configs
      template:
        src: nxos_bgp.j2
        dest: "./configs/tmp/{{ inventory_hostname }}_2_bgp.txt"
    - name: assamble all configs
      assemble:
        src: "./configs/tmp/"
        dest: "./configs/{{ inventory_hostname }}.txt"
        regexp: "{{ inventory_hostname }}"
